### ISSUE TITLE
Hanging up

### ISSUE THREAD

**Issue by igjaegle** [JeffersonLab/gluex_MCwrapper#18]
Since the change to the new bash script, the simulation is hanging up at:

JANA >>Created JCalibration object of type: JCalibrationCCDB
JANA >>Generated via: JCalibration using CCDB for MySQL and SQLite databases
JANA >>Run:61341
JANA >>URL: mysql://ccdb_user@hallddb-farm.jlab.org/ccdb
JANA >>context: variation=mc
JANA >>comment: Variation for simulations with data conditions
In G4HelixMixedStepper: Choosing Stepper for small steps. Choice is G4ClassicalRK4
JANA >>Creating DGeometry:
JANA >>  Run requested:61341  found:61341
JANA >>  Run validity range: 61341-61341
JANA >>  URL="xmlfile:///group/halld/Software/builds/Linux_CentOS7-x86_64-gcc4.8.5/hdds/hdds-4.6.0/main_HDDS.xml"  context="default"
JANA >>  Type="JGeometryXML"
JANA >>Found 25 material maps in calib. DB

Is it a problem with the database connection?

tks ig.

PS: I put my modified MakeMC_ig.sh in the ijaegle_primex branch

**Comment by T-Britton** [comment]
This is not an issue with gluex_MCwrapper. @markito3 mentioned switching back to sqlite yesterday because the beefier server is not beefy enough. This is a server load issue probably....

**Comment by aaust** [comment]
MCWrapper still switches back to hallddb-farm:
https://github.com/JeffersonLab/gluex_MCwrapper/blob/master/MakeMC.csh#L202

**Comment by T-Britton** [comment]
MCwrapper has not updated the default location.  There is no switching/switching back.  Part of the problem is the cat is out of the bag and there are releases pointing to different default locations.  I also don't want to get in to the business of a flavor of month, nor site specific configurations (too much).  the work around is simply to set the ccdb_sqlite variable in MC.config to point to the /group/dist/ccdb.sqlite .  The -farm is not technically broken as far as MCwrapper is concerned

**Comment by sdobbs** [comment]
Shouldn't there be a consistent way to override the environment settings that MCWrapper has?  I thought you could set that in the environment file.  I agree that MCwrapper shouldn't worry too much about site-specific configurations - in that case, it shouldn't be pointing to hallddb-farm, then...

---Sean

On Thu, Jan 9, 2020 at 10:02 AM T-Britton <notifications@github.com<mailto:notifications@github.com>> wrote:

MCwrapper has not updated the default location. There is no switching/switching back. Part of the problem is the cat is out of the bag and there are releases pointing to different default locations. I also don't want to get in to the business of a flavor of month, nor site specific configurations (too much). the work around is simply to set the ccdb_sqlite variable in MC.config to point to the /group/dist/ccdb.sqlite . The -farm is not technically broken as far as MCwrapper is concerned

**Comment by T-Britton** [comment]
There is the ability to set things via the configuration either at the MC.config level or via custom MakeMC.  I can consider making that specific option a little more flexible then it already is...

Its existence in MCwrapper was historical and was done at the behest of Mark I and all of sci comp because Peter got a lot of jobs going at once and took down the group disk. Then it just used mysql, but then came the storms.  Mark I asked if I could direct jobs to another location by default, thus "jlab_batch_default" was created.  ALL of this is not a problem or issue with MCwrapper, it is an issue with the systems that need to be relied on; whether that means a beefier DB server to handle the loads (was supposed to be the purpose of the -farm), or ensuring the underlying file system doesn't have a file locking issue. There must be a default method.  I could remove all of the jlab specific stuff...but then there will be whole new host of issues that will crop up. So it is a catch 22 which MCwrapper has no power/control over....and is thus not an MCwrapper issue, or perhaps, should not be an mcwrapper issue.
