### ISSUE TITLE
Requested Max photon energy is above the electron beam energy rcdb!

### ISSUE THREAD

**Issue by markdalton** [JeffersonLab/gluex_MCwrapper#41]
I update my mcwrapper to the current master and am getting a crash simulating run 51768.

> something went wrong with initialization
> Error: Requested Max photon energy 11.0 is above the electron beam energy rcdb!
> ending gluex_MC.py
> 

It does not matter what value of energy is used.

Config file here:

> gluex_MC.py /home/dalton/gluex/FCAL/MC_omega3pi_E6to11.6_FCAL.config 51768 10 
>

Aside: the value obtained from rcdb should be output in this error message.

**Comment by T-Britton** [comment]
let me address the aside first:  It is being printed out; "electron beam energy rcdb" really should be "electron beam energy 11.6" or something.  because the user can provide the ebeam energy I use the string "rcdb" as a keyword to tell mcwrapper to "look it up".  

something is going wrong when it is attempting to read the energy from the rcdb.  It is on my radar and I will look into it in the next 24 hours or so

**Comment by markdalton** [comment]
I verified that the DEV branch does this too.

**Comment by T-Britton** [comment]
I believe this is solved as a user configuration error....reopen if it isn't solved
