### ISSUE TITLE
SubmitSim's example generator config filename is unhelpful

### ISSUE THREAD

**Issue by nsjarvis** [JeffersonLab/gluex_MCwrapper#47]
It starts with /.../Generators and the text is too large to fit into the box so the entire thing is not readable. 
It is not obvious how to interpret /.../  
I suggest that you remove the text or make it a lot shorter and more realistic, eg /home/username/gen_amp_2pi.cfg

**Comment by T-Britton** [comment]
when I did that I got a lot of submissions and emails because people put /home/ in and provided no read access.  When I switched to this form the number of bad submits due to permissions issues went way down. I can't use two dots because that could be interpreted as a relative path.  And if I use any more dots less useful information will be shown.  The length of that bar is screen size/window size dependent (among other things) and will not be fixed

**Comment by nsjarvis** [comment]
If /home is by default private, then I agree, that is a terrible example.  

How about /work/halld/username/gen.cfg  instead ?

**Comment by T-Britton** [comment]
When I made it /work/ I got a lot of "does it have to be on work?".  Maybe, no example, it does say full path.  Replace with: "path must be accessible by tbritton on an ifarm machine"

**Comment by T-Britton** [comment]
updated placeholder
