### ISSUE TITLE
Default RCDB query in gluex_MC.py seems incorrect (does not depend on RunPeriod)

### ISSUE THREAD

**Issue by keigo-miz** [JeffersonLab/gluex_MCwrapper#92]
I tried to generate 2019-11 MC data, and gluex_MC.py returned the empty run-list table.

I think this is because of the following line:
https://github.com/JeffersonLab/gluex_MCwrapper/blob/160440aaa35382e3614c3bfaaa261ff3050d9a28/gluex_MC.py#L1587

Here, "@is_production and @status_approved" is used as a default query, but this query should depend on the run period (for example, "@is_dirc_production and @status_approved" should be used for 2019-11 data).

Can somebody modify this part so that we can generate 2019-11 MC data with gluex_MC.py script?

**Comment by keigo-miz** [comment]
Alex A. told me that RCDB_QUERY directive should be specified in the MCwrapper configuration file, and I'm now able to generate 2019-11 MC samples.

In the example configuration file below, this RCDB_QUERY directive is not used (commented out). Maybe this part should be modified?
https://github.com/JeffersonLab/gluex_MCwrapper/blob/160440aaa35382e3614c3bfaaa261ff3050d9a28/examples/MC.config#L9

**Comment by s6pepaul** [comment]
Hi Keigo,

the line is commented out because it was never needed for 2017-01 data, which was the standard data set when MCwrapper was created. You only need it for more recent beam times.

You might have a point, it might be worthwhile to uncomment this and make sure people set it as they need it. I will change that.

Cheers,
Peter

**Comment by keigo-miz** [comment]
Hi Peter,

Thank you for your reply. I'm gonna close this issue.

Best,
Keigo
